export const ROUTES = {
  root: '/',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  alunos: '/alunos',
  aluno: '/aluno/:id',
  agenda: '/agenda',
  financeiro: '/financeiro',
  relatorios: '/relatorios',
  dietas: '/dietas',
  treinos: '/treinos',
  perfil: '/perfil',
  configuracoes: '/configuracoes',
  ajuda: '/help',
  planos: '/planos',
} as const;
